/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BD.Conexion;
import Clases.Factura;
import Clases.Recibo;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emiliano
 */
public class RecuperarComprobantes extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarRecibos
     */
    public RecuperarComprobantes() {
        initComponents();
        this.setTitle("Recuperar comprobantes");
        this.setLocationRelativeTo(null);
        this.jTable1.getColumnModel().getColumn(6).setMinWidth(0);
        this.jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        this.jTable1.getColumnModel().getColumn(6).setWidth(0);

        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();

        List<Factura> ListaFact = Conexion.getInstance().listarFacturasDeshabilitados();
        for (int i = 0; i < ListaFact.size(); i++) {
            String numeroComp = ListaFact.get(i).getSerieComprobante() + "-" + ListaFact.get(i).getNroComprobante();
            model.addRow(new Object[]{ListaFact.get(i).getFecha().toString(), ListaFact.get(i).getTipo().toString(),
                numeroComp, ListaFact.get(i).getMoneda().toString(), ListaFact.get(i).getTotal(), "Deshabilitado", ListaFact.get(i)});
        }

        List<Recibo> ListaRec = Conexion.getInstance().listarRecibosDeshabilitados();
        for (int i = 0; i < ListaRec.size(); i++) {
            String numeroComp = ListaRec.get(i).getSerieComprobante() + "-" + ListaRec.get(i).getNroComprobante();
            model.addRow(new Object[]{ListaRec.get(i).getFecha().toString(), "Recibo",
                numeroComp, ListaRec.get(i).getMoneda().toString(), String.valueOf(ListaRec.get(i).getTotal()), "Deshabilitado", ListaRec.get(i)});
        }
        if(ListaFact.isEmpty() && ListaRec.isEmpty()){
            this.jButton1.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Tipo", "Numero", "Moneda", "Total", "Estado", "Objeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Habilitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = this.jTable1.getSelectedRow();
        if (row != -1) {
            if (this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 6) instanceof Factura) {
                Factura fac = (Factura) this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 6);
                fac.setDeshabilitado(false);
                Conexion.getInstance().merge(fac);
                ((DefaultTableModel)this.jTable1.getModel()).removeRow(this.jTable1.getSelectedRow());
                if(this.jTable1.getRowCount()==0){
                    this.jButton1.setEnabled(false);
                }
                javax.swing.JOptionPane.showMessageDialog(this, "La factura se ha habilitado correctamente.");
            } else if (this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 6) instanceof Recibo) {
                Recibo rec = (Recibo) this.jTable1.getModel().getValueAt(this.jTable1.getSelectedRow(), 6);
                rec.setDeshabilitado(false);
                Conexion.getInstance().merge(rec);
                ((DefaultTableModel)this.jTable1.getModel()).removeRow(this.jTable1.getSelectedRow());
                if(this.jTable1.getRowCount()==0){
                    this.jButton1.setEnabled(false);
                }
                javax.swing.JOptionPane.showMessageDialog(this, "El recibo se ha habilitado correctamente.");
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un comprobante.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarComprobantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarComprobantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarComprobantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarComprobantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarComprobantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
